### ISSUE TITLE
'walks in/arrives' Break

### ISSUE THREAD

**Issue by Teronias** [jdalley/tecext#14]
Mostly seen in high spawn areas such as Signal Tower Island or the Rat Pits.  If a target arrives just as the, "You are no longer busy" displays then the script will stall until the next, "walks in/arrives" or manual /resume. @jdalley

**Comment by jdalley** [comment]
Ahh interesting, yes I could see how that would happen. I'll try and find a workaround for this.

**Comment by Teronias** [comment]
![script failure](https://github.com/jdalley/tecext/assets/157252474/1ba4c144-dec9-405f-a11d-f37b9e98a71a)

Here is the example from my archer.

AND -- here is the script I'm using:

    {
        "addAttack": false,
        "commandList": [
            {
                "command": "quicksh",
                "parse": [
                    {
                        "moveNextNow": true,
                        "outcome": "isn't loaded"
                    },
                    {
                        "moveNextWhen": "You are no longer busy",
                        "outcome": "You quickly raise your"
                    }
                ]
            }
        ],
        "continueOnWalkIn": true,
        "scriptFriendlyName": "Archery Quickshot Only",
        "scriptName": "archQuick",
        "scriptType": "combat",
        "shouldKill": true,
        "shouldKillParse": "you twist sharply",
        "stanceCommand": "",
        "weaponItemName": ""
    },

**Comment by Teronias** [comment]
Delay seems a good fix!

**Comment by jdalley** [comment]
I don't have a really solid fix for this that works across all types of scripts - but the recent addition of the "CMD Retry" feature in the General tab of the extension popup. If you set this to be low it'll auto restart the script if it hasn't sent a command in that amount of time.
