### ISSUE TITLE
AIM'ing Breaks kill command

### ISSUE THREAD

**Issue by Teronias** [jdalley/tecext#15]
When attacking a specific area of the body...

i.e. /start archshot "sea|sail neck"
Result: "When the TARGET falls unconscious: "Neck" is not necessary; try again without it."

The desire is for the TARGET to be killed regardless of the AIM.

@jdalley

**Comment by jdalley** [comment]
@Teronias  the current way this is supported is if you write the script to have <target> in and write the aiming you intend for it.

```
{
  "command": "pslash <target> high",
  "parse": [
    {
      "moveNextWhen": "You are no longer busy",
      "outcome": "Sliding your front leg back"
    },
    {
      "moveNextWhen": "You are no longer busy",
      "outcome": "You start to fumble"
    }
  ]
},
```
